package main

import (
	"math/rand"
)

var wordList = []string{
	"the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
	"it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
	"this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
	"or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
	"so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
	"when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
	"people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
	"than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
	"back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
	"even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
	"is", "are", "was", "were", "been", "being", "has", "had", "does", "did",
	"very", "just", "should", "now", "here", "where", "why", "how", "when", "while",
	"each", "few", "more", "some", "such", "no", "nor", "too", "very", "can",
	"will", "just", "should", "now", "than", "then", "once", "here", "there", "when",
	"where", "why", "how", "all", "each", "every", "both", "few", "more", "most",
	"other", "some", "such", "only", "own", "same", "than", "too", "very", "just",
	"about", "after", "before", "between", "under", "again", "further", "once", "during", "through",
	"above", "below", "against", "without", "within", "along", "among", "around", "behind", "beyond",
	"never", "always", "often", "still", "already", "almost", "away", "back", "down", "home",
	"inside", "outside", "together", "apart", "instead", "rather", "simply", "quite", "enough", "much",
	"life", "only", "show", "world", "still", "school", "try", "tell", "keep", "last",
	"never", "old", "leave", "feel", "seem", "next", "turn", "great", "small", "big",
	"high", "long", "right", "left", "hand", "eye", "place", "case", "thing", "point",
	"kind", "end", "part", "house", "area", "group", "family", "country", "problem", "fact",
	"business", "night", "water", "room", "mother", "area", "money", "story", "fact", "month",
	"lot", "right", "study", "book", "eye", "job", "word", "business", "issue", "side",
	"kind", "head", "house", "life", "form", "support", "person", "thing", "point", "world",
	"school", "state", "family", "student", "group", "country", "problem", "hand", "part", "place",
	"case", "week", "company", "system", "program", "question", "work", "government", "number", "night",
	"hand", "data", "water", "money", "story", "body", "service", "market", "music", "point",
	"power", "hour", "game", "line", "end", "member", "law", "car", "city", "community",
	"name", "team", "minute", "idea", "kid", "parent", "face", "door", "health", "history",
	"party", "result", "morning", "reason", "research", "girl", "guy", "food", "moment", "air",
	"teacher", "force", "education", "office", "help", "policy", "heart", "culture", "science", "mind",
	"report", "role", "period", "plan", "test", "road", "rule", "foot", "care", "blood",
	"walk", "art", "land", "record", "interest", "size", "phone", "shot", "price", "piece",
	"top", "bottom", "age", "death", "tax", "war", "law", "letter", "behind", "above",
	"below", "across", "against", "along", "among", "around", "before", "behind", "beneath", "beside",
	"between", "beyond", "during", "except", "inside", "minus", "near", "outside", "past", "round",
	"since", "through", "under", "until", "upon", "within", "without", "according", "across", "after",
	"against", "along", "among", "around", "because", "before", "behind", "below", "beneath", "beside",
	"between", "beyond", "during", "except", "inside", "into", "like", "minus", "near", "off",
	"onto", "outside", "over", "past", "plus", "round", "since", "through", "toward", "under",
	"until", "upon", "with", "within", "without", "able", "about", "above", "abroad", "according",
	"across", "actually", "after", "again", "against", "ahead", "all", "almost", "alone", "along",
	"already", "also", "although", "always", "among", "and", "another", "any", "anybody", "anyhow",
	"anyone", "anything", "anyway", "anywhere", "apart", "appear", "appreciate", "appropriate", "are", "around",
	"aside", "ask", "available", "away", "awfully", "back", "be", "became", "because", "become",
	"been", "before", "behind", "being", "believe", "below", "beside", "best", "better", "between",
	"beyond", "both", "brief", "but", "by", "came", "can", "cannot", "cant", "cause",
	"causes", "certain", "certainly", "changes", "clearly", "c'mon", "co", "com", "come", "comes",
	"concerning", "consequently", "consider", "considering", "contain", "containing", "contains", "could", "couldn't", "course",
	"c'mon", "currently", "definitely", "described", "despite", "did", "didn't", "different", "do", "does",
	"doesn't", "doing", "done", "don't", "down", "downwards", "during", "each", "edu", "eight",
	"either", "else", "elsewhere", "enough", "entirely", "especially", "et", "etc", "even", "ever",
	"every", "everybody", "everyone", "everything", "everywhere", "ex", "exactly", "example", "except", "far",
	"few", "fifth", "first", "five", "followed", "following", "follows", "for", "former", "formerly",
	"forth", "four", "from", "further", "furthermore", "get", "gets", "getting", "given", "gives",
	"go", "goes", "going", "gone", "got", "gotten", "greetings", "had", "hadn't", "happens",
	"hardly", "has", "hasn't", "have", "haven't", "having", "he", "hello", "help", "hence",
	"her", "here", "hereafter", "hereby", "herein", "here's", "hereupon", "hers", "herself", "him",
	"himself", "his", "hither", "hopefully", "how", "howbeit", "however", "hundred", "i'd", "ie",
	"if", "ignored", "i'll", "i'm", "immediate", "in", "inasmuch", "inc", "indeed", "infinite",
	"inner", "insofar", "instead", "into", "inward", "isn't", "it", "it'd", "it'll", "it's",
	"its", "itself", "i've", "just", "k", "keep", "keeps", "kept", "know", "known",
	"knows", "last", "lately", "later", "latter", "latterly", "least", "less", "lest", "let",
	"let's", "like", "liked", "likely", "little", "look", "looking", "looks", "ltd", "mainly",
	"many", "may", "maybe", "me", "mean", "meantime", "meanwhile", "merely", "might", "more",
	"moreover", "most", "mostly", "much", "must", "my", "myself", "name", "namely", "near",
	"nearly", "necessarily", "neither", "never", "nevertheless", "new", "next", "nine", "no", "nobody",
	"non", "none", "noone", "nor", "normally", "not", "nothing", "nowhere", "obviously", "of",
	"off", "often", "okay", "old", "once", "one", "ones", "only", "onto", "or",
	"other", "others", "otherwise", "ought", "our", "ours", "ourselves", "out", "outside", "over",
	"overall", "own", "particular", "particularly", "per", "perhaps", "placed", "plus", "possible", "presumably",
	"probably", "provides", "que", "quite", "qv", "rather", "rd", "re", "really", "reasonably",
	"regarding", "regardless", "regards", "relatively", "respectively", "right", "said", "same", "saw", "say",
	"saying", "says", "second", "secondly", "see", "seeing", "seem", "seemed", "seeming", "seems",
	"seen", "self", "selves", "sensible", "serious", "seriously", "seven", "several", "shall", "she",
	"should", "shouldn't", "since", "six", "so", "some", "somebody", "somehow", "someone", "something",
	"sometime", "sometimes", "somewhat", "somewhere", "soon", "sorry", "specified", "specify", "specifying", "still",
	"sub", "such", "sup", "sure", "take", "taken", "tell", "tends", "th", "than",
	"thank", "thanks", "thanx", "that", "that'll", "thats", "that've", "the", "their", "theirs",
	"them", "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", "there's",
	"thereupon", "these", "they", "they'd", "they'll", "they're", "they've", "think", "third", "this",
	"thorough", "thoroughly", "those", "though", "three", "through", "throughout", "thru", "thus", "to",
	"together", "too", "took", "toward", "towards", "tried", "tries", "truly", "try", "trying",
	"twice", "two", "un", "under", "unfortunately", "unless", "unlikely", "until", "unto", "up",
	"upon", "us", "use", "used", "useful", "uses", "using", "usually", "value", "various",
	"very", "via", "viz", "vs", "want", "wants", "was", "wasn't", "way", "we",
	"we'd", "welcome", "well", "we'll", "went", "were", "we're", "weren't", "we've", "what",
	"whatever", "what'll", "what's", "what've", "when", "whence", "whenever", "where", "whereafter", "whereas",
	"whereby", "wherein", "where's", "whereupon", "wherever", "whether", "which", "while", "whither", "who",
	"who'd", "who'll", "who's", "whoever", "whole", "whom", "who've", "whose", "why", "willing",
	"wish", "with", "within", "without", "won't", "wonder", "would", "wouldn't", "yes", "yet",
	"you", "you'd", "you'll", "your", "you're", "yours", "yourself", "yourselves", "you've", "zero",
}

// getRandomWords returns n random words from the word list
func getRandomWords(n int) []string {
	words := make([]string, n)
	for i := 0; i < n; i++ {
		words[i] = wordList[rand.Intn(len(wordList))]
	}
	return words
}
